on:
  workflow_dispatch:

name: Test Live Mode

jobs:
  test-falco-live:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Start Falco
      uses: falcosecurity/falco-actions/start@dbd1251c3b5e2aef470b1e08b883629ee53ab373
      with:
        mode: live
        falco-version: '0.39.0'
        verbose: true
        
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Read Sensitive File
      run: |
        sleep 3
        docker run --rm --privileged ubuntu cat /etc/shadow
        sleep 3

    - name: Id
      run: |
        id
        groups

    - name: Stop Falco
      uses: falcosecurity/falco-actions/stop@dbd1251c3b5e2aef470b1e08b883629ee53ab373
      with:
        mode: live
        verbose: true
  
  test-falco-live-custom-rule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Start Falco
      uses: falcosecurity/falco-actions/start@dbd1251c3b5e2aef470b1e08b883629ee53ab373
      with:
        mode: live
        falco-version: '0.39.0'
        custom-rule-file: '${{ github.workspace }}/rules/falco_cicd_rules.yaml'
        verbose: true

    - name: Checkout
      uses: actions/checkout@v4

    - name: Overwrite Source Code
      shell: bash
      run: |
        sleep 3
        echo "pwned" > ${{ github.workspace }}/pwn.txt
        sleep 3

    - name: Stop Falco
      uses: falcosecurity/falco-actions/stop@dbd1251c3b5e2aef470b1e08b883629ee53ab373
      with:
        mode: live
        verbose: true
